ci_service: travis_ci
ci_access_token: AZjohYADPKQAwMGZApzXR7cEaIaKvOsBJ
coverage_service: coveralls
xcodeproj: OptimizelySDKiOS/OptimizelySDKiOS.xcodeproj
scheme: OptimizelySDKiOS
workspace: OptimizelySDK.xcworkspace
configuration: Release